# Generated by Django 5.2.5 on 2025-08-10 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_core', '0003_alter_scheduledtask_user_alter_taskconfig_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='config',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskconfig',
            name='user',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], default='queued', max_length=10)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ExecutionLog',
        ),
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
        migrations.DeleteModel(
            name='TaskConfig',
        ),
    ]
